name: Criterion tests
on: [push]
env:
  LD_LIBRARY_PATH: ./criterion-2.4.2/lib
jobs:
  criterion-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
    - uses: actions/checkout@v2
    - name: print env vars
      run: env
    - name: Install valgrind
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind
    - name: Create Criterion test suit
      run: make
    - name: Run Criterion test suit
      run: make