name: Criterion tests
on: [push]
jobs:
  criterion-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
    - uses: actions/checkout@v2
    - name: Export Dynamic Lib
      run: export LD_LIBRARY_PATH=$PWD/criterion-2.4.2/lib
    - name: print env vars
      run: env
    - name: Run Criterion test suit
      run: make